### ISSUE TITLE
Ch02: Memory layout image missing

### ISSUE THREAD

**Issue by yjamal** [ayende/libgavran#1]
From chapter 2 doc:

![image](https://user-images.githubusercontent.com/36642280/85809404-61257200-b71d-11ea-835c-ad1d09b63167.png)

It is pointing to: https://github.com/ayende/libgavran/blob/master/ch02/%7Bimg-src%7D/fig1.png however no such folder/file in the ch02 directory. 

Edit: 
Just quickly skimmed through a couple other chapters and seem to be the same case with them -- missing asset folder/images. 
 
Edit 2: 
Ahh, I see you have the images under the root(repo) folder however you're referencing them relative to the chapters, should be a quick fix. 

Thanks,

**Comment by ayende** [comment]
How are you reading this? If you are reading this on GitHub, that isn't meant to work.
You need to run `asciidoctor` and that would set things up properly, including pulling the right code samples, etc.

**Comment by yj7o5** [comment]
Yea was having a little hard to time to follow just reading .adoc files but yup I have got it building the html doc via asciidoctor. Loving it so far! Thanks

**Comment by yj7o5** [comment]
Although I think you have got this section mixed up a bit. The formatting seems off:
![image](https://user-images.githubusercontent.com/7938533/86321161-0d73c680-bbfe-11ea-97ed-4682fc8e8c6f.png)

**Comment by ayende** [comment]
Yes, looks like copy/paste error, fixed.
