### ISSUE TITLE
Few broken refs between adoc and code snippets

### ISSUE THREAD

**Issue by Cheappie** [ayende/libgavran#2]
Hi, It seems that few refs are broken in chapter 17, from what I have seen either code snippet is in some other file or there is a small typo that makes tag invalid.

#### Warnings generated by asciidoctor
```

asciidoctor: WARNING: ch17.adoc: line 352: unexpected end tag 'btree_multi_get_next' at line 222 of include file: 
libgavran/ch17/code/btree.multi.c
asciidoctor: WARNING: ch17.adoc: line 352: tag 'btree_multi_get_next' not found in include file: 
libgavran/ch17/code/btree.multi.c
asciidoctor: WARNING: ch17.adoc: line 576: tag 'hash_get_entries_count' not found in include file: 
libgavran/ch17/code/hash.multi.c
asciidoctor: WARNING: ch17.adoc: line 602: tag 'hash_drop_with_nesting' not found in include file: 
libgavran/ch17/code/hash.multi.c

```

#### The way how I have fixed these issues

ch17.adoc, both refs define hash.c as a `source`, however in `include` they refer to hash.multi.c
```
-include::./code/hash.multi.c[tags=hash_get_entries_count]
+include::./code/hash.c[tags=hash_get_entries_count]
-include::./code/hash.multi.c[tags=hash_drop_with_nesting]
+include::./code/hash.c[tags=hash_drop_with_nesting]
```

btree.multi.c, closing bracket occurs twice
```
-// tag::btree_multi_get_next[]]
+// tag::btree_multi_get_next[]
```

hash.c, seems like `hash_get_entries_count` is the correct tag
```
-// tag::hash_get_number_of_entries[]
+// tag::hash_get_entries_count[]
-// end::hash_get_number_of_entries[]
+// end::hash_get_entries_count[]
```

Do you prefer to apply fixes on your own, or could I make a pull request ?

**Comment by ayende** [comment]
A pull request would be wonderful, yes.
Thanks.

**Comment by Cheappie** [comment]
here It is https://github.com/ayende/libgavran/pull/3. Everything seems alright now, feel free to merge It
